[tool.poetry]
name = "sagery"
version = "0.1.0"
description = ""
authors = ["Dmitriy Shikhalev <dmitriy.shikhalev@gmail.com>"]
license = "BSD 3-Clause License"
readme = "README.md"
packages = [{ include = "sagery" }]

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.29"
alembic = "^1.13.1"
pydantic = "^2.9.1"

pydantic-settings = "^2.4.0"
[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
poetry = "^1.8.2"
mypy = "^1.9.0"
pytest-coverage = "^0.0"
pylint = "^3.1.0"
pytest-pylint = "^0.21.0"
pytest-mypy = "^0.10.3"

httpx = "^0.27.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sagery = "sagery.main:main"

