"""Add statuses to Job and Request

Revision ID: 07040cc27090
Revises: d915837537a6
Create Date: 2024-04-06 19:56:28.271130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07040cc27090'
down_revision: Union[str, None] = 'd915837537a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'ROLLINGBACK', 'ROLLEDBACK', name='jobstatus'), nullable=True))
    op.add_column('request', sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', name='requeststatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'status')
    op.drop_column('job', 'status')
    # ### end Alembic commands ###
