"""init migration

Revision ID: 6b751fd3bf3d
Revises: 
Create Date: 2024-06-18 20:42:08.700132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b751fd3bf3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('saga',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_key'), 'data', ['key'], unique=False)
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_name'), 'input', ['name'], unique=False)
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_name'), 'output', ['name'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saga_operator_table',
    sa.Column('saga_name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.ForeignKeyConstraint(['saga_name'], ['saga.name'], ),
    sa.PrimaryKeyConstraint('saga_name', 'operator_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saga_operator_table')
    op.drop_table('request')
    op.drop_index(op.f('ix_output_name'), table_name='output')
    op.drop_table('output')
    op.drop_index(op.f('ix_input_name'), table_name='input')
    op.drop_table('input')
    op.drop_index(op.f('ix_data_key'), table_name='data')
    op.drop_table('data')
    op.drop_table('saga')
    op.drop_table('operator')
    op.drop_table('job')
    # ### end Alembic commands ###
