"""empty message

Revision ID: 5bd4101c88f4
Revises: 
Create Date: 2024-10-07 15:51:28.665377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bd4101c88f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE IF EXISTS status')

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('vars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vars_job_id'), 'vars', ['job_id'], unique=False)
    op.create_index('uix_job_var', 'vars', ['job_id', 'name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['vars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_index'), 'items', ['index'], unique=False)
    op.create_index(op.f('ix_items_key'), 'items', ['key'], unique=False)
    op.create_index(op.f('ix_items_var_id'), 'items', ['var_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['var_id'], ['vars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_index'), 'requests', ['index'], unique=False)
    op.create_index(op.f('ix_requests_job_id'), 'requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_requests_operator_name'), 'requests', ['operator_name'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_var_id'), 'requests', ['var_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_var_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_operator_name'), table_name='requests')
    op.drop_index(op.f('ix_requests_job_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_index'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_items_var_id'), table_name='items')
    op.drop_index(op.f('ix_items_key'), table_name='items')
    op.drop_index(op.f('ix_items_index'), table_name='items')
    op.drop_table('items')
    op.drop_index('uix_job_var', table_name='vars')
    op.drop_index(op.f('ix_vars_job_id'), table_name='vars')
    op.drop_table('vars')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
