"""empty message

Revision ID: 1a3573791d7b
Revises: 
Create Date: 2024-09-27 08:37:33.523280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3573791d7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('branch_job_name_unique', 'branches', ['job_id', 'name'], unique=True)
    op.create_index(op.f('ix_branches_job_id'), 'branches', ['job_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('items_key', 'items', ['job_id', 'key'], unique=False)
    op.create_index(op.f('ix_items_job_id'), 'items', ['job_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'DONE', 'FAILED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_job_id'), 'requests', ['job_id'], unique=False)
    op.create_table('branch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_items')
    op.drop_index(op.f('ix_requests_job_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_items_job_id'), table_name='items')
    op.drop_index('items_key', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_branches_job_id'), table_name='branches')
    op.drop_index('branch_job_name_unique', table_name='branches')
    op.drop_table('branches')
    op.drop_table('jobs')
    # ### end Alembic commands ###
