"""empty message

Revision ID: b6e2d9b29eac
Revises: 9ebb4fe9c830
Create Date: 2024-10-15 10:55:47.753736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e2d9b29eac'
down_revision: Union[str, None] = '9ebb4fe9c830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('managed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'managed')
    # ### end Alembic commands ###
