"""empty message

Revision ID: f7859b94748d
Revises: ebe6a14c918c
Create Date: 2024-10-17 07:31:37.810306

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7859b94748d'
down_revision: Union[str, None] = 'ebe6a14c918c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_calls', sa.Column('pos', sa.Integer(), nullable=False))
    op.drop_index('uix_job_function_call', table_name='function_calls')
    op.create_index('uix_job_function_call', 'function_calls', ['job_id', 'pos'], unique=True)
    op.drop_column('function_calls', 'num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_calls', sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('uix_job_function_call', table_name='function_calls')
    op.create_index('uix_job_function_call', 'function_calls', ['job_id', 'num'], unique=True)
    op.drop_column('function_calls', 'pos')
    # ### end Alembic commands ###
