"""Init migration

Revision ID: 25bc47ac1ffc
Revises: 
Create Date: 2024-04-07 12:04:43.478305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc47ac1ffc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BLOCKING', 'RUNNING', 'DONE', 'FAILED', 'ROLLINGBACK', 'ROLLEDBACK', name='jobstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('saga',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', name='requeststatus'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saga_operator_table',
    sa.Column('saga_name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.ForeignKeyConstraint(['saga_name'], ['saga.name'], ),
    sa.PrimaryKeyConstraint('saga_name', 'operator_name')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_operator_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_operator_data')
    op.drop_table('output')
    op.drop_table('input')
    op.drop_table('data')
    op.drop_table('saga_operator_table')
    op.drop_table('request')
    op.drop_table('saga')
    op.drop_table('operator')
    op.drop_table('job')
    # ### end Alembic commands ###
