"""Add Request.external_id

Revision ID: c26de07862c0
Revises: 71f986d379b3
Create Date: 2024-04-07 11:59:45.328429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26de07862c0'
down_revision: Union[str, None] = '71f986d379b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'external_id')
    # ### end Alembic commands ###
