"""Added Saga table

Revision ID: cc5bfdd0f814
Revises: 
Create Date: 2024-04-06 12:40:22.093923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5bfdd0f814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('saga',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saga_operator_table',
    sa.Column('saga_name', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['operator_name'], ['operator.name'], ),
    sa.ForeignKeyConstraint(['saga_name'], ['saga.name'], ),
    sa.PrimaryKeyConstraint('saga_name', 'operator_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saga_operator_table')
    op.drop_table('request')
    op.drop_table('data')
    op.drop_table('saga')
    op.drop_table('operator')
    op.drop_table('job')
    # ### end Alembic commands ###
