"""empty message

Revision ID: 1de6b9ce8709
Revises: 4b763be5909a
Create Date: 2026-09-14 10:01:44.431747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de6b9ce8709'
down_revision: Union[str, Sequence[str], None] = '4b763be5909a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('launch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'values', 'launches', ['launch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.drop_column('values', 'launch_id')
    # ### end Alembic commands ###
