"""empty message

Revision ID: 972b245f2ac4
Revises: 5472bf80d04e
Create Date: 2026-10-09 19:18:36.094858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '972b245f2ac4'
down_revision: Union[str, Sequence[str], None] = '5472bf80d04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('launches', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('launches', 'state')
    # ### end Alembic commands ###
