"""fix models

Revision ID: 9e04c85c5998
Revises: b44cf92df828
Create Date: 2026-09-24 08:54:00.647439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e04c85c5998'
down_revision: Union[str, Sequence[str], None] = 'b44cf92df828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inputs_operator_id_fkey'), 'inputs', type_='foreignkey')
    op.create_foreign_key("inputs_operators_idx", 'inputs', 'operators', ['operator_id'], ['id'])
    op.drop_constraint(op.f('outputs_operator_id_fkey'), 'outputs', type_='foreignkey')
    op.create_foreign_key("outputs_operators_idx", 'outputs', 'operators', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("outputs_operators_idx", 'outputs', type_='foreignkey')
    op.create_foreign_key(op.f('outputs_operator_id_fkey'), 'outputs', 'sagas', ['operator_id'], ['id'])
    op.drop_constraint("inputs_operators_idx", 'inputs', type_='foreignkey')
    op.create_foreign_key(op.f('inputs_operator_id_fkey'), 'inputs', 'sagas', ['operator_id'], ['id'])
    # ### end Alembic commands ###
