"""empty message

Revision ID: e2227e4c7ab2
Revises: 6cf86ab71301
Create Date: 2026-09-17 11:29:17.216142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2227e4c7ab2'
down_revision: Union[str, Sequence[str], None] = '6cf86ab71301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('queue_id', sa.Integer(), nullable=False))
    op.create_foreign_key("streams_queue_id_fkey", 'streams', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("streams_queue_id_fkey", 'streams', type_='foreignkey')
    op.drop_column('streams', 'queue_id')
    # ### end Alembic commands ###
