"""empty message

Revision ID: 4b763be5909a
Revises: dce0d95621d8
Create Date: 2026-09-13 17:50:43.585938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b763be5909a'
down_revision: Union[str, Sequence[str], None] = 'dce0d95621d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('streams', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('values', sa.Column('stream_id', sa.Integer(), nullable=False))
    op.add_column('values', sa.Column('done', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('values_queue_id_fkey'), 'values', type_='foreignkey')
    op.drop_constraint(op.f('values_job_id_fkey'), 'values', type_='foreignkey')
    op.create_foreign_key(None, 'values', 'streams', ['stream_id'], ['id'])
    op.drop_column('values', 'queue_id')
    op.drop_column('values', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('values', sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.create_foreign_key(op.f('values_job_id_fkey'), 'values', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('values_queue_id_fkey'), 'values', 'queues', ['queue_id'], ['id'])
    op.drop_column('values', 'done')
    op.drop_column('values', 'stream_id')
    op.drop_column('streams', 'done')
    op.drop_table('launches')
    # ### end Alembic commands ###
