"""Init migration

Revision ID: c0bb81b63678
Revises: zero
Create Date: 2026-09-14 10:21:34.499761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0bb81b63678'
down_revision: Union[str, Sequence[str], None] = 'zero'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'name', name='uq_queue')
    )
    op.create_index(op.f('ix_queues_name'), 'queues', ['name'], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'queue_id', name='uq_inputs')
    )
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_launches_status'), 'launches', ['status'], unique=False)
    op.create_table('operator_input_queue',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id')
    )
    op.create_table('operator_output_queue',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id')
    )
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'queue_id', name='uq_outputs')
    )
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_done'), 'streams', ['done'], unique=False)
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('launch_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['launch_id'], ['launches.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_done'), 'values', ['done'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_values_done'), table_name='values')
    op.drop_table('values')
    op.drop_index(op.f('ix_streams_done'), table_name='streams')
    op.drop_table('streams')
    op.drop_table('outputs')
    op.drop_table('operator_output_queue')
    op.drop_table('operator_input_queue')
    op.drop_index(op.f('ix_launches_status'), table_name='launches')
    op.drop_table('launches')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_queues_name'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('sagas')
    # ### end Alembic commands ###
