"""Initial migration

Revision ID: fadb71eb0ac6
Revises: 
Create Date: 2026-07-26 19:11:43.224019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadb71eb0ac6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sagas_name'), 'sagas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sagas_name'), table_name='sagas')
    op.drop_table('sagas')
    # ### end Alembic commands ###
