"""fix bug

Revision ID: 6cf86ab71301
Revises: c0bb81b63678
Create Date: 2026-09-15 20:54:41.786300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf86ab71301'
down_revision: Union[str, Sequence[str], None] = 'c0bb81b63678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('operator_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_inputs'), 'inputs', type_='unique')
    op.create_unique_constraint('uq_inputs', 'inputs', ['operator_id', 'queue_id'])
    op.drop_constraint(op.f('inputs_saga_id_fkey'), 'inputs', type_='foreignkey')
    op.create_foreign_key("inputs_operator_id_fkey", 'inputs', 'sagas', ['operator_id'], ['id'])
    op.drop_column('inputs', 'saga_id')
    op.add_column('outputs', sa.Column('operator_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_outputs'), 'outputs', type_='unique')
    op.create_unique_constraint('uq_outputs', 'outputs', ['operator_id', 'queue_id'])
    op.drop_constraint(op.f('outputs_saga_id_fkey'), 'outputs', type_='foreignkey')
    op.create_foreign_key("outputs_operator_id_fkey", 'outputs', 'sagas', ['operator_id'], ['id'])
    op.drop_column('outputs', 'saga_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('saga_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("outputs_operator_id_fkey", 'outputs', type_='foreignkey')
    op.create_foreign_key(op.f('outputs_saga_id_fkey'), 'outputs', 'sagas', ['saga_id'], ['id'])
    op.drop_constraint('uq_outputs', 'outputs', type_='unique')
    op.create_unique_constraint(op.f('uq_outputs'), 'outputs', ['saga_id', 'queue_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('outputs', 'operator_id')
    op.add_column('inputs', sa.Column('saga_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("inputs_operator_id_fkey", 'inputs', type_='foreignkey')
    op.create_foreign_key(op.f('inputs_saga_id_fkey'), 'inputs', 'sagas', ['saga_id'], ['id'])
    op.drop_constraint('uq_inputs', 'inputs', type_='unique')
    op.create_unique_constraint(op.f('uq_inputs'), 'inputs', ['saga_id', 'queue_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inputs', 'operator_id')
    # ### end Alembic commands ###
