"""add inputs/outputs

Revision ID: dce0d95621d8
Revises: fadb71eb0ac6
Create Date: 2026-09-13 17:00:43.585684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce0d95621d8'
down_revision: Union[str, Sequence[str], None] = 'fadb71eb0ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.CHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_name'), 'queues', ['name'], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'queue_id', name='uq_inputs')
    )
    op.create_table('operator_input_queue',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id')
    )
    op.create_table('operator_output_queue',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id')
    )
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'queue_id', name='uq_outputs')
    )
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_sagas_name'), table_name='sagas')
    op.create_unique_constraint(None, 'sagas', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sagas', type_='unique')
    op.create_index(op.f('ix_sagas_name'), 'sagas', ['name'], unique=False)
    op.drop_table('values')
    op.drop_table('streams')
    op.drop_table('outputs')
    op.drop_table('operator_output_queue')
    op.drop_table('operator_input_queue')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_queues_name'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    op.drop_table('jobs')
    # ### end Alembic commands ###
