"""fix models

Revision ID: 5472bf80d04e
Revises: 9e04c85c5998
Create Date: 2026-09-24 09:44:43.105007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5472bf80d04e'
down_revision: Union[str, Sequence[str], None] = '9e04c85c5998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_input_queue')
    op.drop_table('operator_output_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_output_queue',
    sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('operator_output_queue_operator_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('operator_output_queue_queue_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id', name=op.f('operator_output_queue_pkey'))
    )
    op.create_table('operator_input_queue',
    sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('operator_input_queue_operator_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('operator_input_queue_queue_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'queue_id', name=op.f('operator_input_queue_pkey'))
    )
    # ### end Alembic commands ###
